apiVersion: kafka.strimzi.io/v1beta2
kind: KafkaTopic
metadata:
  name: pega-cdc-events
  labels:
    strimzi.io/cluster: pega-kafka
spec:
  partitions: 3
  replicas: 1
  config:
    retention.ms: 604800000
    segment.bytes: 1073741824
