apiVersion: karpenter.k8s.aws/v1
kind: EC2NodeClass
metadata:
  name: default
spec:
  subnetSelectorTerms:
    - tags:
        karpenter.sh/discovery: eks-prod
  securityGroupSelectorTerms:
    - tags:
        karpenter.sh/discovery: eks-prod
