apiVersion: kafka.strimzi.io/v1beta2
kind: Kafka
metadata:
  name: pega-kafka
spec:
  kafka:
    replicas: 3
    config:
      offsets.topic.replication.factor: 2
      transaction.state.log.replication.factor: 2
      default.replication.factor: 2
      min.insync.replicas: 2
    resources:
      requests:
        cpu: 500m
        memory: 1Gi
      limits:
        cpu: "1"
        memory: 2Gi
  zookeeper:
    replicas: 3
