apiVersion: apps/v1
kind: Deployment
metadata:
  name: pega-web
spec:
  replicas: 2
  template:
    spec:
      containers:
        - name: pega-web
          resources:
            requests:
              cpu: 250m
              memory: 256Mi
            limits:
              cpu: 500m
              memory: 512Mi
