apiVersion: argoproj.io/v1alpha1
kind: AppProject
metadata:
  name: pega-platform
  namespace: argocd
spec:
  description: Pega Platform multi-cluster deployment project
  sourceRepos:
    - https://github.com/suryayelagam/argocd-kustomize-explore.git
  destinations:
    # Local demo: all cluster secrets resolve to the same Kind cluster,
    # so we use server wildcard + namespace pattern.
    # Production: replace with explicit name/namespace pairs per cluster.
    - server: '*'
      namespace: 'pega-*'
  clusterResourceWhitelist:
    - group: ""
      kind: Namespace
    - group: karpenter.sh
      kind: NodePool
    - group: karpenter.k8s.aws
      kind: EC2NodeClass
  namespaceResourceWhitelist:
    - group: ""
      kind: "*"
    - group: apps
      kind: "*"
    - group: networking.k8s.io
      kind: "*"
    - group: autoscaling
      kind: "*"
    - group: policy
      kind: "*"
    - group: kafka.strimzi.io
      kind: "*"
    - group: karpenter.sh
      kind: "*"
    - group: karpenter.k8s.aws
      kind: "*"
