apiVersion: apps/v1
kind: Deployment
metadata:
  name: pega-web
spec:
  replicas: 1
  template:
    spec:
      containers:
        - name: pega-web
          resources:
            requests:
              cpu: 100m
              memory: 128Mi
            limits:
              cpu: 250m
              memory: 256Mi
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: pega-batch
spec:
  replicas: 1
  template:
    spec:
      containers:
        - name: pega-batch
          resources:
            requests:
              cpu: 100m
              memory: 128Mi
            limits:
              cpu: 250m
              memory: 256Mi
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: pega-stream
spec:
  replicas: 1
  template:
    spec:
      containers:
        - name: pega-stream
          resources:
            requests:
              cpu: 100m
              memory: 128Mi
            limits:
              cpu: 250m
              memory: 256Mi
