apiVersion: kafka.strimzi.io/v1beta2
kind: Kafka
metadata:
  name: pega-kafka
spec:
  kafka:
    replicas: 1
    resources:
      requests:
        cpu: 100m
        memory: 256Mi
      limits:
        cpu: 250m
        memory: 512Mi
  zookeeper:
    replicas: 1
